/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS CICLOS */

-- CILCOS -> CREATE == EXEC CICLOS_CREATE 'MENSUAL'
CREATE PROCEDURE CICLOS_CREATE
@tipo VARCHAR(15),
@ciclo INT
AS BEGIN
    INSERT INTO CICLOS (tipo, ciclo) VALUES (@tipo, @ciclo)
END
GO

-- CICLOS -> READ ALL ==EXEC CICLOS_READ_ALL
CREATE PROCEDURE CICLOS_READ_ALL
AS 
    SELECT * FROM CICLOS
GO

-- CICLOS -> READ ACTIVES == EXEC CICLOS_READ_ACTIVES
CREATE PROCEDURE CICLOS_READ_ATIVES
AS 
    SELECT * FROM CICLOS WHERE estado = 1
GO

-- CILOS -> READ INACTIVE == EXEC CICLOS_READ_INACTIVES
CREATE PROCEDURE CICLOS_READ_INACTIVES
AS
    SELECT * FROM CICLOS WHERE estado = 0
GO

-- CICLOS ->  READ ONE == EXEC CICLOS_READ_ONE
CREATE PROCEDURE CICLOS_READ_ONE
@id INT
AS
    SELECT * FROM CICLOS WHERE id = @id
GO

--CICLOS ->  UPDATE == EXEC CICLOS_UPDATE
CREATE PROCEDURE CICLOS_UPDATE
@id INT,
@tipo VARCHAR(15),
@ciclo INT
AS
    UPDATE CICLOS SET
    tipo = @tipo,
    ciclo = @ciclo
    WHERE id = @id
GO

-- CICLOS -> CHANGE STATUS = EXEC CICLOS_DELETE
CREATE PROCEDURE CICLOS_DELETE
@id INT
AS BEGIN
    UPDATE CICLOS SET estado = 0
    WHERE id = @id
END
GO

-- CICLOS -> CHANGE STATUS = EXEC CICLOS_RESTORE
CREATE PROCEDURE CICLOS_RESTORE
@id INT
AS BEGIN
    UPDATE CICLOS SET estado = 1
    WHERE id = @id
END
GO

/* FIN PROCEDIMIENTOS ALMACENADOS CICLOS */
/* ====================================== */