USE MANAGE_IT
GO

/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS CICLOS */

-- CILCOS -> CREATE == EXEC CICLOS_CREATE 'MENSUAL'
CREATE PROCEDURE CICLOS_CREATE
@id CHAR(8),
@tipo VARCHAR(15),
@ciclo INT
AS BEGIN
    DECLARE @id CHAR(8)
    SELECT @id = 'CLC' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)) FROM CICLOS
    INSERT INTO CICLOS VALUES (
        @id, @tipo, @ciclo, @estado, '1'
    )
END
GO

-- CICLOS -> READ ALL ==EXEC CICLOS_READ_ALL
CREATE PROCEDURE CICLOS_READ_ALL
AS 
    SELECT *FROM CICLOS
GO

-- CICLOS -> READ ACTIVES == EXEC CICLOS_READ_ACTIVES
CREATE PROCEDURE CICLOS_READ_ATIVES
AS 
    SELECT * FROM CICLOS WHERE estado = '1'
GO

-- CILOS -> READ INACTIVE == EXEC CICLOS_READ_INACTIVES
CREATE PROCEDURE CICLOS_READ_IN
AS
    SELECT * FROM CICLOS WHERE estado = '0'
GO

