USE MANAGE_IT
GO

/* ========================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS HISTORIALES */

-- HISTORIALES -> CREATE == EXEC HISTORIALES_CREATE 'English'
CREATE PROCEDURE HISTORIALES_CREATE
@id_usuario CHAR(8),
@id_proveedor CHAR(8),
@monto DECIMAL(5,2)
AS BEGIN
	DECLARE @id CHAR(11)
	SELECT @id = 'HIS' + RIGHT('00000000' + LTRIM(STR(COUNT(*) + 1)), 8) FROM HISTORIALES
	INSERT INTO HISTORIALES VALUES (
        @id, @id_usuario, @id_proveedor,
        @monto, GETDATE()
    )
END
GO

-- HISTORIALES -> READ ALL == EXEC HISTORIALES_READ_ALL
CREATE PROCEDURE HISTORIALES_READ_ALL
AS
	SELECT * FROM HISTORIALES
GO

-- HISTORIALES -> READ ONE == EXEC HISTORIALES_READ_ONE
CREATE PROCEDURE HISTORIALES_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM HISTORIALES WHERE id = @id
GO

-- HISTORIALES -> SEARCH == EXEC HISTORIALES_SEARCH
CREATE PROCEDURE HISTORIALES_SEARCH
@search VARCHAR(50)
AS
	SELECT * FROM HISTORIALES WHERE
        id_usuario LIKE(CONCAT('%', @search, '%')) OR
        id_proveedor LIKE(CONCAT('%', @search, '%'))
GO

/* FIN PROCEDIMIENTOS ALMACENADOS HISTORIALES */
/* ====================================== */