
GO
/* INICIO PROCEDIMINETO ALMACENADO MONEDA*/
/* =============================================== */

-- MONEDA -> CREATE = EXEC == MONEDA_CREATE ''
CREATE PROCEDURE MONEDAS_CREATE
@moneda VARCHAR(12),
@estado BIT
AS BEGIN
    DECLARE @id CHAR(8)
    SELECT @id = 'MON' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM MONEDAS
    INSERT INTO MONEDAS VALUES(@id ,@moneda, @estado)
END
GO

-- MONEDA READ ALL = EXEC MONEDA_READ_ALL
CREATE PROCEDURE MONEDAS_READ_ALL
AS
    SELECT * FROM MONEDAS
GO

-- MONEDA READ ACTIVE = EXEC USUARIOS_READ_ACTIVES
CREATE PROCEDURE MONEDAS_READ_ACTIVES
AS
    SELECT * FROM MONEDAS WHERE estado = '1'
GO
-- MONEDA READ INACTIVES = EXEC MONEDA_READ_INACTIVES
CREATE PROCEDURE MONEDAS_READ_INACTIVES
AS
    SELECT * FROM MONEDAS WHERE estado = '0'
GO



-- MONEDA SEARCH == EXEC MONEDAS_SEARCH
CREATE PROCEDURE MONEDAS_SEARCH
@search VARCHAR(50)
AS
     SELECT * FROM MONEDAS WHERE moneda LIKE(CONCAT('%', @search))
GO

-- MONEDA UPDATE == EXEC MONEDAS_UPDATE
CREATE PROCEDURE MONEDA_UPDATE
@id CHAR(8),
@moneda VARCHAR(12),
@estado BIT
AS
    UPDATE MONEDAS SET 
		id = @id,
		moneda = @moneda,
		estado = @estado
		WHERE id = @id
GO

/* ====================================== */
--USUARIOS -> DELETE USER == EXEC MONEDA_DELETE
CREATE PROCEDURE MONEDA_DELETE
@id CHAR(8)
AS 
    UPDATE MONEDAS SET estado = '0' WHERE id = @id
GO
--USUARIOS -> DELETE USER == EXEC MONEDA_RESTORE
CREATE PROCEDURE MONEDA_RESTORE
@id CHAR(8)
AS 
    UPDATE MONEDAS SET estado = '1' WHERE id = @id
/* FIN PROCEDIMIENTOS ALMACENADOS MONEDAS*/
/* ====================================== */