/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS IDIOMAS */

-- CILCOS -> CREATE == EXEC IDIOMAS_CREATE 'MENSUAL'
CREATE PROCEDURE IDIOMAS_CREATE
@idioma VARCHAR(12)
AS BEGIN
    INSERT INTO IDIOMAS (idioma) VALUES (@idioma)
END
GO

-- IDIOMAS -> READ ALL ==EXEC IDIOMAS_READ_ALL
CREATE PROCEDURE IDIOMAS_READ_ALL
AS 
    SELECT * FROM IDIOMAS
GO

-- IDIOMAS -> READ ACTIVES == EXEC IDIOMAS_READ_ACTIVES
CREATE PROCEDURE IDIOMAS_READ_ACTIVES
AS 
    SELECT * FROM IDIOMAS WHERE estado = 1
GO

-- CILOS -> READ INACTIVE == EXEC IDIOMAS_READ_INACTIVES
CREATE PROCEDURE IDIOMAS_READ_INACTIVES
AS
    SELECT * FROM IDIOMAS WHERE estado = 0
GO

--IDIOMAS ->  UPDATE == EXEC IDIOMAS_UPDATE
CREATE PROCEDURE IDIOMAS_UPDATE
@id INT,
@idioma VARCHAR(15)
AS
    UPDATE IDIOMAS SET
    idioma = @idioma
    WHERE id = @id
GO

-- IDIOMAS -> CHANGE STATUS = EXEC IDIOMAS_DELETE
CREATE PROCEDURE IDIOMAS_DELETE
@id INT
AS BEGIN
    UPDATE IDIOMAS SET estado = 0
    WHERE id = @id
END
GO

-- IDIOMAS -> CHANGE STATUS = EXEC IDIOMAS_RESTORE
CREATE PROCEDURE IDIOMAS_RESTORE
@id INT
AS BEGIN
    UPDATE IDIOMAS SET estado = 1
    WHERE id = @id
END
GO

/* FIN PROCEDIMIENTOS ALMACENADOS IDIOMAS */
/* ====================================== */