<<<<<<< HEAD
USE MANAGE_IT
GO

/* ========================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS IDIOMAS */

-- IDIOMAS -> CREATE == EXEC IDIOMAS_CREATE 'English'
CREATE PROCEDURE IDIOMAS_CREATE
@idioma VARCHAR(12)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'IDI' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM IDIOMAS
	INSERT INTO IDIOMAS VALUES (@id, @idioma, '1')
END
GO

-- IDIOMAS -> READ ALL == EXEC IDIOMAS_READ_ALL
CREATE PROCEDURE IDIOMAS_READ_ALL
AS
	SELECT * FROM IDIOMAS
=======
/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS IDIOMAS */

-- CILCOS -> CREATE == EXEC IDIOMAS_CREATE 'MENSUAL'
CREATE PROCEDURE IDIOMAS_CREATE
@idioma VARCHAR(12)
AS BEGIN
    INSERT INTO IDIOMAS (idioma) VALUES (@idioma)
END
GO

-- IDIOMAS -> READ ALL ==EXEC IDIOMAS_READ_ALL
CREATE PROCEDURE IDIOMAS_READ_ALL
AS 
    SELECT * FROM IDIOMAS
>>>>>>> 59354bc2a0d81346b344d8a5de05ef5c4dd8c78d
GO

-- IDIOMAS -> READ ACTIVES == EXEC IDIOMAS_READ_ACTIVES
CREATE PROCEDURE IDIOMAS_READ_ACTIVES
<<<<<<< HEAD
AS
	SELECT * FROM IDIOMAS WHERE	estado = '1'
GO

-- IDIOMAS -> READ INACTIVES == EXEC IDIOMAS_READ_INACTIVES
CREATE PROCEDURE IDIOMAS_READ_INACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '0'
GO

	SELECT * FROM IDIOMAS WHERE idioma LIKE(CONCAT('%', @idioma, '%'))
GO

-- IDIOMAS -> UPDATE == EXEC IDIOMAS_UPDATE
CREATE PROCEDURE IDIOMAS_UPDATE
@id		CHAR(8),
@idioma VARCHAR(12),
@estado BIT
AS
	UPDATE IDIOMAS SET
	idioma = @idioma,
	estado = @estado
	WHERE id = @id
GO

-- IDIOMAS -> CHANGE STATUS == EXEC IDIOMAS_CHANGE_STATUS
CREATE PROCEDURE IDIOMAS_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM IDIOMAS WHERE id = @id
	IF @estado = 1
		UPDATE IDIOMAS SET estado = '0' WHERE id = @id
	ELSE
		UPDATE IDIOMAS SET estado = '1' WHERE id = @id
=======
AS 
    SELECT * FROM IDIOMAS WHERE estado = 1
GO

-- CILOS -> READ INACTIVE == EXEC IDIOMAS_READ_INACTIVES
CREATE PROCEDURE IDIOMAS_READ_INACTIVES
AS
    SELECT * FROM IDIOMAS WHERE estado = 0
GO

--IDIOMAS ->  UPDATE == EXEC IDIOMAS_UPDATE
CREATE PROCEDURE IDIOMAS_UPDATE
@id INT,
@idioma VARCHAR(15)
AS
    UPDATE IDIOMAS SET
    idioma = @idioma
    WHERE id = @id
GO

-- IDIOMAS -> CHANGE STATUS = EXEC IDIOMAS_DELETE
CREATE PROCEDURE IDIOMAS_DELETE
@id INT
AS BEGIN
    UPDATE IDIOMAS SET estado = 0
    WHERE id = @id
END
GO

-- IDIOMAS -> CHANGE STATUS = EXEC IDIOMAS_RESTORE
CREATE PROCEDURE IDIOMAS_RESTORE
@id INT
AS BEGIN
    UPDATE IDIOMAS SET estado = 1
    WHERE id = @id
END
>>>>>>> 59354bc2a0d81346b344d8a5de05ef5c4dd8c78d
GO

/* FIN PROCEDIMIENTOS ALMACENADOS IDIOMAS */
/* ====================================== */