/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS MONEDAS */

-- CILCOS -> CREATE == EXEC MONEDAS_CREATE 'MENSUAL'
CREATE PROCEDURE MONEDAS_CREATE
@moneda VARCHAR(12),
@cambio DECIMAL(7, 2)
AS BEGIN
    INSERT INTO MONEDAS (moneda, cambio) VALUES (@moneda, @cambio)
END
GO

-- MONEDAS -> READ ALL ==EXEC MONEDAS_READ_ALL
CREATE PROCEDURE MONEDAS_READ_ALL
AS 
    SELECT * FROM MONEDAS
GO

-- MONEDAS -> READ ACTIVES == EXEC MONEDAS_READ_ACTIVES
CREATE PROCEDURE MONEDAS_READ_ACTIVES
AS 
    SELECT * FROM MONEDAS WHERE estado = 1
GO

-- CILOS -> READ INACTIVE == EXEC MONEDAS_READ_INACTIVES
CREATE PROCEDURE MONEDAS_READ_INACTIVES
AS
    SELECT * FROM MONEDAS WHERE estado = 0
GO

-- MONEDAS ->  READ ONE == EXEC MONEDAS_READ_ONE
CREATE PROCEDURE MONEDAS_READ_ONE
@id INT
AS
    SELECT * FROM MONEDAS WHERE id = @id
GO

--MONEDAS ->  UPDATE == EXEC MONEDAS_UPDATE
CREATE PROCEDURE MONEDAS_UPDATE
@id INT,
@moneda VARCHAR(12),
@cambio DECIMAL(7, 2)
AS
    UPDATE MONEDAS SET
    moneda = @moneda,
    cambio = @cambio
    WHERE id = @id
GO

-- MONEDAS -> CHANGE STATUS = EXEC MONEDAS_DELETE
CREATE PROCEDURE MONEDAS_DELETE
@id INT
AS BEGIN
    UPDATE MONEDAS SET estado = 0
    WHERE id = @id
END
GO

-- MONEDAS -> CHANGE STATUS = EXEC MONEDAS_RESTORE
CREATE PROCEDURE MONEDAS_RESTORE
@id INT
AS BEGIN
    UPDATE MONEDAS SET estado = 1
    WHERE id = @id
END
GO

/* FIN PROCEDIMIENTOS ALMACENADOS MONEDAS */
/* ====================================== */