USE MANAGE_IT
GO
/* INICIO PROCEDIMINETO ALMACENADO MONEDA*/
/* =============================================== */

-- MONEDA -> CREATE = EXEC == MONEDA_CREATE ''
CREATE PROCEDURE MONEDA_CREATE
@modeda VARCHAR(12),
@estado BIT
AS BEGIN
    DECLARE @id CHAR(8)
    SELECT @id = 'MON' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM MONEDA
    INSERT INTO CICLOS VALUES(@moneda, @estado)
END
GO

-- MONEDA READ ALL = EXEC MONEDA_READ_ALL
CREATE PROCEDURE MONEDA_READ_ALL
AS
    SELECT * FROM MONEDA
GO

-- MONEDA READ ACTIVE = EXEC USUARIOS_READ_ACTIVES
CREATE PROCEDURE MONEDA_READ_ACTIVES
AS
    SELECT * FROM MONEDA WHERE estado = '1'
GO
-- MONEDA READ INACTIVES = EXEC MONEDA_READ_INACTIVES
CREATE PROCEDURE MONEDA_READ_INACTIVES
AS
    SELECT * FROM MONEDA WHERE estado = '0'
GO

-- MONEDA READ ONE == EXEC MONEDA_READ_ONE
CREATE PROCEDURE MONEDA_READ_ONE
@id CHAR(8)
AS
    SELECT * FROM MONEDA WHERE id = @id
GO

-- MONEDA SEARCH == EXEC MONEDA_SEARCH
CREATE PROCEDURE MONEDA_SEARCH
@search VARCHAR(50)
AS
     SELECT * FROM MONEDA WHERE
     moneda LIKE(CONCAT('%', @search))
GO

-- MONEDA UPDATE == EXEC MONEDA_UPDATE
CREATE PROCEDURE MONEDA_UPDATE
@id CHAR(8),
@modeda VARCHAR(12),
@estado BIT
AS
    UPDATE MONEDA SET
    moneda = @moneda,
    estado = @estado
    WHERE id = @id
GO
--- MONEDA CHANGE STATUS == EXEC MONEDA_CHANGES_STATUS
CREATE PROCEDURE MONEDA_CHANGES_STATUS
AS 
    DECLARE @estado BIT
    SELECT @estado = estado FROM MONEDA where id= @id
    IF @estado = 1
        UPDATE MONEDA SET estado = '0' WHERE id = @id
    ELSE 
        UPDATE MONEDA SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS MONEDA */
/* ====================================== */

