USE MANAGE_IT
GO

/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS PERSONA_JURIDICA */

-- PERSONA_JURIDICA -> CREATE == EXEC PERSONA_JURIDICA_CREATE 'English'

CREATE PROCEDURE PERSONA_JURIDICA_CREATE
	@razonSocial VARCHAR(250),
	@ruc CHAR(11),
	@id_servicio CHAR(8),
	@tel1 VARCHAR(15),
	@tel2 VARCHAR(15),
	@correo VARCHAR(320),
	@direccion VARCHAR(320)
AS
BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'PJU' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5)
	FROM PERSONA_NATURAL
	INSERT INTO PERSONA_JURIDICA
	VALUES
		(
			@id, @razonSocial, @ruc, @id_servicio,
			@tel1, @tel2, @correo, @direccion, '1'
	)
END
GO

-- PERSONA_JURIDICA -> READ ALL == EXEC PERSONA_JURIDICA_READ_ALL
CREATE PROCEDURE PERSONA_JURIDICA_READ_ALL
AS
SELECT *
FROM PERSONA_JURIDICA
GO

-- PERSONA_JURIDICA -> READ ACTIVES == EXEC PERSONA_JURIDICA_READ_ACTIVES
CREATE PROCEDURE PERSONA_JURIDICA_READ_ACTIVES
AS
SELECT *
FROM PERSONA_JURIDICA
WHERE	estado = '1'
GO

-- PERSONA_JURIDICA -> READ INACTIVES == EXEC PERSONA_JURIDICA_READ_INACTIVES
CREATE PROCEDURE PERSONA_JURIDICA_READ_INACTIVES
AS
SELECT *
FROM PERSONA_JURIDICA
WHERE	estado = '0'
GO

-- PERSONA_JURIDICA -> READ ONE == EXEC PERSONA_JURIDICA_READ_ONE
CREATE PROCEDURE PERSONA_JURIDICA_READ_ONE
	@id CHAR(8)
AS
SELECT *
FROM PERSONA_JURIDICA
WHERE id = @id
GO

-- PERSONA_JURIDICA -> SEARCH == EXEC PERSONA_JURIDICA_SEARCH
CREATE PROCEDURE PERSONA_JURIDICA_SEARCH
	@search VARCHAR(50)
AS
SELECT *
FROM PERSONA_JURIDICA
WHERE
		razonSocial LIKE(CONCAT('%', @search, '%')) OR
	ruc LIKE(CONCAT('%', @search, '%'))
GO

-- PERSONA_JURIDICA -> UPDATE == EXEC PERSONA_JURIDICA_UPDATE
CREATE PROCEDURE PERSONA_JURIDICA_UPDATE
	@id CHAR(8),
	@razonSocial VARCHAR(250),
	@ruc CHAR(11),
	@id_servicio CHAR(8),
	@tel1 VARCHAR(15),
	@tel2 VARCHAR(15),
	@correo VARCHAR(320),
	@direccion VARCHAR(320),
	@estado BIT
AS
UPDATE PERSONA_JURIDICA SET
	razonSocial = @razonSocial,
	ruc = @ruc,
	id_servicio = @id_servicio,
	tel1 = @tel1,
	tel2 = @tel2,
	correo = @correo,
	direccion = @direccion,
	estado = @estado
	WHERE id = @id
GO

-- ELEIMAR CERVICIO

CREATE PROCEDURE PERSONA_JURIDICA_DELETE
	@ID CHAR(8)
AS
UPDATE PERSONA_JURIDICA SET estado ='0' WHERE id = @ID
GO
-- ACTIVAR CERVICIO
CREATE PROCEDURE PERSONA_JURIDICA_RESTORE
	@ID CHAR(8)
AS
UPDATE PERSONA_JURIDICA SET estado ='1' WHERE id = @ID
GO
@id_servicio CHAR
(8),
@tel1 VARCHAR
(15),
@tel2 VARCHAR
(15),
@correo VARCHAR
(320),
@direccion VARCHAR
(320)
AS
BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'PJU' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5)
	FROM PERSONA_NATURAL
	INSERT INTO PERSONA_JURIDICA
	VALUES
		(
			@id, @razonSocial, @ruc, @id_servicio,
			@tel1, @tel2, @correo, @direccion, '1'
	)
END
GO

-- PERSONA_JURIDICA -> READ ALL == EXEC PERSONA_JURIDICA_READ_ALL
CREATE PROCEDURE PERSONA_JURIDICA_READ_ALL
AS
SELECT *
FROM PERSONA_JURIDICA
GO

-- PERSONA_JURIDICA -> READ ACTIVES == EXEC PERSONA_JURIDICA_READ_ACTIVES
CREATE PROCEDURE PERSONA_JURIDICA_READ_ACTIVES
AS
SELECT *
FROM PERSONA_JURIDICA
WHERE	estado = '1'
GO

-- PERSONA_JURIDICA -> READ INACTIVES == EXEC PERSONA_JURIDICA_READ_INACTIVES
CREATE PROCEDURE PERSONA_JURIDICA_READ_INACTIVES
AS
SELECT *
FROM PERSONA_JURIDICA
WHERE	estado = '0'
GO

-- PERSONA_JURIDICA -> READ ONE == EXEC PERSONA_JURIDICA_READ_ONE
CREATE PROCEDURE PERSONA_JURIDICA_READ_ONE
	@id CHAR(8)
AS
SELECT *
FROM PERSONA_JURIDICA
WHERE id = @id
GO

-- PERSONA_JURIDICA -> SEARCH == EXEC PERSONA_JURIDICA_SEARCH
CREATE PROCEDURE PERSONA_JURIDICA_SEARCH
	@search VARCHAR(50)
AS
SELECT *
FROM PERSONA_JURIDICA
WHERE
		razonSocial LIKE(CONCAT('%', @search, '%')) OR
	ruc LIKE(CONCAT('%', @search, '%'))
GO

-- PERSONA_JURIDICA -> UPDATE == EXEC PERSONA_JURIDICA_UPDATE
CREATE PROCEDURE PERSONA_JURIDICA_UPDATE
	@id CHAR(8),
	@razonSocial VARCHAR(250),
	@ruc CHAR(11),
	@id_servicio CHAR(8),
	@tel1 VARCHAR(15),
	@tel2 VARCHAR(15),
	@correo VARCHAR(320),
	@direccion VARCHAR(320),
	@estado BIT
AS
UPDATE PERSONA_JURIDICA SET
	razonSocial = @razonSocial,
	ruc = @ruc,
	id_servicio = @id_servicio,
	tel1 = @tel1,
	tel2 = @tel2,
	correo = @correo,
	direccion = @direccion,
	estado = @estado
	WHERE id = @id
GO

-- ELEIMAR CERVICIO

CREATE PROCEDURE PERSONA_JURIDICA_DELETE
	@ID CHAR(8)
AS
UPDATE PERSONA_JURIDICA SET estado ='0' WHERE id = @ID
GO
-- ACTIVAR CERVICIO
CREATE PROCEDURE PERSONA_JURIDICA_RESTORE
	@ID CHAR(8)
AS
UPDATE PERSONA_JURIDICA SET estado ='1' WHERE id = @ID
GO

/* FIN PROCEDIMIENTOS ALMACENADOS PERSONA JURIDICA*/

/* FIN PROCEDIMIENTOS ALMACENADOS PERSONA_JURIDICA */
/* ====================================== */