USE MANAGE_IT
GO

/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS PERSONA_NATURAL */

-- PERSONA_NATURAL -> CREATE == EXEC PERSONA_NATURAL_CREATE 'English'
CREATE PROCEDURE PERSONA_NATURAL_CREATE
@apePater VARCHAR(15),
@apeMater VARCHAR(15),
@nombres VARCHAR(45),
@dni CHAR(8),
@id_servicio CHAR(8),
@tel1 VARCHAR(15),
@tel2 VARCHAR(15),
@correo VARCHAR(320),
@direccion VARCHAR(250)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'PNA' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM PERSONA_NATURAL
	INSERT INTO PERSONA_NATURAL VALUES (
		@id, @apePater, @apeMater, @nombres, @dni,
		@id_servicio, @tel1, @tel2, @correo, @direccion, '1'
	)
END
GO

-- PERSONA_NATURAL -> READ ALL == EXEC PERSONA_NATURAL_READ_ALL
CREATE PROCEDURE PERSONA_NATURAL_READ_ALL
AS
	SELECT * FROM PERSONA_NATURAL
GO

-- PERSONA_NATURAL -> READ ACTIVES == EXEC PERSONA_NATURAL_READ_ACTIVES
CREATE PROCEDURE PERSONA_NATURAL_READ_ACTIVES
AS
	SELECT * FROM PERSONA_NATURAL WHERE	estado = '1'
GO

-- PERSONA_NATURAL -> READ INACTIVES == EXEC PERSONA_NATURAL_READ_INACTIVES
CREATE PROCEDURE PERSONA_NATURAL_READ_INACTIVES
AS
	SELECT * FROM PERSONA_NATURAL WHERE	estado = '0'
GO

-- PERSONA_NATURAL -> READ ONE == EXEC PERSONA_NATURAL_READ_ONE
CREATE PROCEDURE PERSONA_NATURAL_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM PERSONA_NATURAL WHERE id = @id
GO

-- PERSONA_NATURAL -> SEARCH == EXEC PERSONA_NATURAL_SEARCH
CREATE PROCEDURE PERSONA_NATURAL_SEARCH
@search VARCHAR(50)
AS
	SELECT * FROM PERSONA_NATURAL WHERE
		apePater LIKE(CONCAT('%', @search, '%')) OR
		apeMater LIKE(CONCAT('%', @search, '%')) OR
		nombres LIKE(CONCAT('%', @search, '%')) OR
		dni LIKE(CONCAT('%', @search, '%'))
GO

-- PERSONA_NATURAL -> UPDATE == EXEC PERSONA_NATURAL_UPDATE
CREATE PROCEDURE PERSONA_NATURAL_UPDATE
@id CHAR(8),
@apePater VARCHAR(15),
@apeMater VARCHAR(15),
@nombres VARCHAR(45),
@dni CHAR(8),
@id_servicio CHAR(8),
@tel1 VARCHAR(15),
@tel2 VARCHAR(15),
@correo VARCHAR(320),
@direccion VARCHAR(250),
@estado BIT
AS
	UPDATE PERSONA_NATURAL SET
	apePater = @apePater,
	apeMater = @apeMater,
	nombres = @nombres,
	dni = @dni,
	id_servicio = @id_servicio,
	tel1 = @tel1,
	tel2 = @tel2,
	correo = @correo,
	direccion = @direccion,
	estado = @estado
	WHERE id = @id
GO

-- delete
CREATE PROCEDURE PERSONA_NATURAL_DELETE
@id CHAR(8)
AS
UPDATE PERSONA_NATURAL SET estado = '0' WHERE id = @id
-- restore
GO
CREATE PROCEDURE PERSONA_NATURAL_RESTORE
@id CHAR(8)
AS
UPDATE PERSONA_NATURAL SET estado = '1' WHERE id = @id

