-- PROVEEDORES -> CEREATE == EXECT IDIOMAS_CREATE 'PAPA, PNA88888'
CREATE PROCEDURE PROVEEDORES_CREATE
@tipo CHAR(1),
@id_per_nat CHAR(8),
@id_per_jur CHAR(8),
@usuario_creacion INT
AS BEGIN
    INSERT INTO PROVEEDORES (
        tipo, id_per_nat, id_per_jur, usuario_creacion
    ) VALUES (
        @tipo, @id_per_nat, @id_per_jur, @usuario_creacion
    )
END

GO

-- PROVEEDORES -> READ ALL == EXEC PROVEEDORES_READ_ALL
CREATE PROCEDURE PROVEEDORES_READ_ALL
@usuario INT
AS
	IF @usuario = 'admin'
		SELECT * FROM PROVEEDORES
	ELSE
		SELECT * FROM PROVEEDORES
		WHERE usuario_creacion = @usuario
GO

-- PROVEEDORES -> READ ACTIVES == EXEC PROVEEDORES_READ_ACTIVES
CREATE PROCEDURE PROVEEDORES_READ_ACTIVES
@usuario INT
AS
	IF @usuario = 'admin'
		SELECT * FROM PROVEEDORES
		WHERE estado = 1
	ELSE
		SELECT * FROM PROVEEDORES
		WHERE 
			usuario_creacion = @usuario AND
			estado = 1
GO

-- PROVEEDORES -> READ INACTIVES == EXEC PROVEEDORES_READ_INACTIVES
CREATE PROCEDURE PROVEEDORES_READ_INACTIVES
@usuario VARCHAR(16)
AS
	IF @usuario = 'admin'
		SELECT * FROM PROVEEDORES
		WHERE estado = 0
	ELSE
		SELECT * FROM PROVEEDORES
		WHERE 
			usuario_creacion = @usuario AND
			estado = 0
GO

-- PROVEEDORES -> UPDATE == EXEC PROVEEDORES_UPDATE
CREATE PROCEDURE PROVEEDORES_UPDATE
@id CHAR(8),
@tipo CHAR(1),
@id_per_nat CHAR(8),
@id_per_jur CHAR(8)
AS
    UPDATE PROVEEDORES SET
    tipo = @tipo,
    id_per_nat = @id_per_nat,
    id_per_jur = @id_per_jur
    WHERE id = @id
GO

-- ELIMINAR PROVEEDOR
CREATE PROCEDURE PROVEEDORES_DELETE
@id INT
AS BEGIN
	UPDATE PROVEEDORES
	SET estado = 0
	WHERE id = @id
END
GO

-- ACTIVAR PROVEEDOR
CREATE PROCEDURE PROVEEDORES_RESTORE
@id CHAR(8)
AS BEGIN
	UPDATE PROVEEDORES
	SET estado = 1
	WHERE id = @id
END
GO
/* FIN DE  PROCEDIMINTO ALMACENADO PROVEEDORES */
/* ===============================================*/
