USE MANAGE_IT
GO

-- PROVEEDORES -> CEREATE == EXECT IDIOMAS_CREATE 'PAPA, PNA88888'
CREATE PROCEDURE PROVEEDORES_CREATE
@tipo CHAR(1),
@id_per_nat CHAR(8),
@id_per_jur CHAR(8)
AS BEGIN
    DECLARE @id CHAR(8)
    SELECT @id = 'PRO'+ RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM PROVEEDORES
    INSERT INTO PROVEEDORES VALUES (@id, @tipo, @id_per_nat, @id_per_jur, '1')
END

GO

-- PROVEEDORES -> READ ALL == EXEC PROVEEDORES_READ_ALL
CREATE PROCEDURE PROVEEDORES_READ_ALL
AS
    SELECT * FROM  PROVEEDORES
GO

--PROVEEDORES -> READ ACTIVES == EXEC PROVEEDORES_READ_ACIVES
CREATE PROCEDURE PEROVEEDORES_READ_ACTIVES
AS
    SELECT * FROM PROVEEDORES WHERE estado = '1'
GO
---PROVEEDORES -> READ INACTIVES == EXEC PROVEEDORES_READ_INACTIVES

CREATE PROCEDURE PROVEEDORES_READ_iNACTIVES
AS
    SELECT * FROM PROVEEDORES WHERE estado = '0'

GO

--PROVEEDORES -> READ ONE == EXEC IDIOMAS_READ_ONE
CREATE PROCEDURE PROVEEDORES_READ_ONE
@id CHAR(8)
AS
    SELECT * FROM PROVEEDORES WHERE id = @id
GO
-- PROVEEDORES -> UPDATE == EXEC PROVEEDORES_UPDATE
CREATE PROCEDURE PROVEEDORES_UPDATE
@id CHAR(8),
@tipo CHAR(1),
@id_per_nat CHAR(8),
@id_per_jur CHAR(8),
@estado BIT

AS
    UPDATE PROVEEDORES SET
    id = @id,
    tipo = @tipo,
    id_per_nat = @id_per_nat,
    id_per_jur = @id_per_jur,
    estado = @estado
    WHERE id = @id
GO

-- PROVEEDORES -> CHANGE STATUS == EXEC PROVEEDORES_CHANGE_STATUS
CREATE PROCEDURE PROVEEDORES_CHANGE_STATUS
@id CHAR(8)
AS
    DECLARE @estado BIT
    SELECT @estado = estado FROM PROVEEDORES WHERE id = @id
    IF @estado = 1
        UPDATE PROVEEDORES SET estado = '0' WHERE id = @id
    else 
        UPDATE PROVEEDORES SET estado = '1' WHERE id = @id
GO
/* FIN DE  PROCEDIMINTO ALMACENADO PROVEEDORES */
/* ===============================================*/
