USE MANAGE_IT
GO

/* =========================================== */
/* INICIO PROCEDIMIENTOS ALMACENADOS SERVICIOS */

-- SERVICIOS -> CREATE == EXEC SERVICIOS_CREATE 'Abarrote'
CREATE PROCEDURE SERVICIOS_CREATE
@servicio VARCHAR(45)
AS BEGIN
	DECLARE @id CHAR(8)  
	SELECT @id = 'SER' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM SERVICIOS
	INSERT INTO SERVICIOS VALUES (@id, @servicio, '1')
END
GO

-- SERVICIOS -> READ ALL == EXEC SERVICIOS_READ_ALL
CREATE PROCEDURE SERVICIOS_READ_ALL
AS
	SELECT * FROM SERVICIOS
GO

-- SERVICIOS -> READ ACTIVES == EXEC SERVICIOS_READ_ACTIVES
CREATE PROCEDURE SERVICIOS_READ_ACTIVES
AS
	SELECT * FROM SERVICIOS WHERE estado = '1'
GO

-- SERVICIOS -> READ INACTIVES == EXEC SERVICIOS_READ_INACTIVES
CREATE PROCEDURE SERVICIOS_READ_INACTIVES
AS
	SELECT * FROM SERVICIOS WHERE estado = '0'
GO

-- SERVICIOS -> READ ONE == EXEC SERVICIOS_READ_ONE
CREATE PROCEDURE SERVICIOS_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM SERVICIOS WHERE id = @id
GO


-- SERVICIOS -> SEARCH == EXEC SERVICIOS_SEARCH
CREATE PROCEDURE SERVICIOS_SEARCH
@servicio VARCHAR(12)
AS
	SELECT * FROM SERVICIOS WHERE servicio LIKE(CONCAT('%', @servicio, '%'))
GO


-- SERVICIOS -> UPDATE == EXEC SERVICIOS_UPDATE
CREATE PROCEDURE SERVICIOS_UPDATE
@id		CHAR(8),
@servicio VARCHAR(12),
@estado BIT
AS
	UPDATE SERVICIOS SET
	servicio = @servicio,
	estado = @estado
	WHERE id = @id
GO

-- ELEIMAR CERVICIO

CREATE PROCEDURE DELETE_SERVICIO
@ID CHAR(8)
AS UPDATE SERVICIOS SET estado ='0' WHERE id = @ID
GO
-- ACTIVAR CERVICIO
CREATE PROCEDURE RESTORE_SERVICIO
@ID CHAR(8)
AS UPDATE SERVICIOS SET estado ='1' WHERE id = @ID
GO
-- ELEIMAR CERVICIO

CREATE PROCEDURE SERVICIOS_DELETE
@ID CHAR(8)
AS UPDATE SERVICIOS SET estado ='0' WHERE id = @ID
GO
-- ACTIVAR CERVICIO
CREATE PROCEDURE SERVICIOS_RESTORE
@ID CHAR(8)
AS UPDATE SERVICIOS SET estado ='1' WHERE id = @ID
GO
