/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS SERVICIOS */

-- CILCOS -> CREATE == EXEC SERVICIOS_CREATE 'MENSUAL'
CREATE PROCEDURE SERVICIOS_CREATE
@servicio VARCHAR(250)
AS BEGIN
    INSERT INTO SERVICIOS (servicio) VALUES (@servicio)
END
GO

-- SERVICIOS -> READ ALL ==EXEC SERVICIOS_READ_ALL
CREATE PROCEDURE SERVICIOS_READ_ALL
AS 
    SELECT * FROM SERVICIOS
GO

-- SERVICIOS -> READ ACTIVES == EXEC SERVICIOS_READ_ACTIVES
CREATE PROCEDURE SERVICIOS_READ_ACTIVES
AS 
    SELECT * FROM SERVICIOS WHERE estado = 1
GO

-- CILOS -> READ INACTIVE == EXEC SERVICIOS_READ_INACTIVES
CREATE PROCEDURE SERVICIOS_READ_INACTIVES
AS
    SELECT * FROM SERVICIOS WHERE estado = 0
GO

--SERVICIOS ->  UPDATE == EXEC SERVICIOS_UPDATE
CREATE PROCEDURE SERVICIOS_UPDATE
@id INT,
@servicio VARCHAR(250)
AS
    UPDATE SERVICIOS SET
    servicio = @servicio
    WHERE id = @id
GO

-- SERVICIOS -> CHANGE STATUS = EXEC SERVICIOS_DELETE
CREATE PROCEDURE SERVICIOS_DELETE
@id INT
AS BEGIN
    UPDATE SERVICIOS SET estado = 0
    WHERE id = @id
END
GO

-- SERVICIOS -> CHANGE STATUS = EXEC SERVICIOS_RESTORE
CREATE PROCEDURE SERVICIOS_RESTORE
@id INT
AS BEGIN
    UPDATE SERVICIOS SET estado = 1
    WHERE id = @id
END
GO

/* FIN PROCEDIMIENTOS ALMACENADOS SERVICIOS */
/* ====================================== */