USE MANAGE_IT
GO
/* INICIO PROCEDIMINETO ALMACENADO USUARIOS*/
/* =============================================== */

-- USUARIOS -> CREATE = EXEC == USUARIOS_CREATE ''
CREATE PROCEDURE USUARIOS_CREATE
(
    @usuario VARCHAR(16),
    @correo VARCHAR(320),
    @clave CHAR(64),
    @dni CHAR(8),
    @apePater VARCHAR(15),
    @apeMater VARCHAR(15),
    @nombres VARCHAR(45),
    @sexo CHAR(1),
    @fec_nac DATE,
    @id_idioma CHAR(8)
)
AS BEGIN 
    DECLARE @id CHAR(8)
    SELECT @id = 'USR' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM USUARIOS
    INSERT INTO USUARIOS VALUES (@id, @usuario, @correo, @clave, @dni, @apePater, @apeMater, @nombre, @sexo, @fec_nac,@id_idioma, '1')
END
GO 

-- USUARIOS -> READ ALL = EXEC USUARIOS_READ_ALL
CREATE PROCEDURE USUARIOS_READ_ALL
AS
    SELECT * FROM USUARIOS
GO

-- USUARIOS -> READ ACTIVES == EXEC USUARIOS_READ_ACTIVES
CREATE PROCEDURE USUARIOS_READ_ACTIVES
AS
    SELECT * FROM USUARIOS WHERE estado = '1'
GO

-- USUARIOS -> READ INACTIVES == EXEC USUARIO_READ_INACTIVES
CREATE PROCEDURE USUARIOS_READ_INACTIVES
AS
    SELECT * FROM USUARIOS WHERE estado = '0'
GO

-- USUARIOS -> READ ONE == EXEC USUARIOS_READ_ONE
CREATE PROCEDURE USUARIOS_READ_ONE
@id CHAR(8)
AS
    SELECT * FROM USUARIOS WHERE id = @id
GO

-- USUARIOS -> SEARCH = EXEC USUARIOS_SEARCH
CREATE PROCEDURE USUARIOS_SEARCH
@search VARCHAR(50)
AS
    SELECT * FROM USUARIOS WHERE
        usuario LIKE(CONCAT('%', @search, '%'))



/*  USUARIO Y CORREO PARA SEARCH* 201 107*/
