
/* ===================================================== */
/* INICIO PROCEDIMINETOS ALACENADOS PROVEEDORES */
USE MANAGE_IT
GO
-- PROVEEDORES -> CEREATE == EXECT IDIOMAS_CREATE 'PAPA, PNA88888'
CREATE PROCEDURE PROVEEDORES_CREATE
@tipo CHAR(1),
@id_per_nat CHAR(8),
@id_per_jur CHAR(8)
AS BEGIN
    DECLARE @id CHAR(8)
    SELECT @id = 'PRO'+ RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM PROVEEDORES
    INSERT INTO PROVEEDORES VALUES (@id, @tipo, @id_per_nat, @id_per_jur, '1')
END

GO

-- PROVEEDORES -> READ ALL == EXEC PROVEEDORES_READ_ALL
CREATE PROCEDURE PROVEEDORES_READ_ALL
AS
    SELECT * FROM  PROVEEDORES
GO

--PROVEEDORES -> READ ACTIVES == EXEC PROVEEDORES_READ_ACIVES
CREATE PROCEDURE PEROVEEDORES_READ_ACTIVES
AS
    SELECT * FROM PROVEEDORES WHERE estado = '1'
GO
---PROVEEDORES -> READ INACTIVES == EXEC PROVEEDORES_READ_INACTIVES

CREATE PROCEDURE PROVEEDORES_READ_iNACTIVES
AS
    SELECT * FROM PROVEEDORES WHERE estado = '0'

GO

--PROVEEDORES -> READ ONE == EXEC IDIOMAS_READ_ONE
CREATE PROCEDURE PROVEEDORES_READ_ONE
@id CHAR(8)
AS
    SELECT * FROM PROVEEDORES WHERE id = @id
GO
-- PROVEEDORES -> UPDATE == EXEC PROVEEDORES_UPDATE
CREATE PROCEDURE PROVEEDORES_UPDATE
@id CHAR(8),
@tipo CHAR(1),
@id_per_nat CHAR(8),
@id_per_jur CHAR(8),
@estado BIT

AS
    UPDATE PROVEEDORES SET
    id = @id,
    tipo = @tipo,
    id_per_nat = @id_per_nat,
    id_per_jur = @id_per_jur,
    estado = @estado
    WHERE id = @id
GO

-- PROVEEDORES -> CHANGE STATUS == EXEC PROVEEDORES_CHANGE_STATUS
CREATE PROCEDURE PROVEEDORES_CHANGE_STATUS
@id CHAR(8)
AS
    DECLARE @estado BIT
    SELECT @estado = estado FROM PROVEEDORES WHERE id = @id
    IF @estado = 1
        UPDATE PROVEEDORES SET estado = '0' WHERE id = @id
    else 
        UPDATE PROVEEDORES SET estado = '1' WHERE id = @id
GO
/* FIN DE  PROCEDIMINTO ALMACENADO PROVEEDORES */
/* ===============================================*/

/* INICIO PROCEDIMINETO ALMACENADO USUARIOS*/
/* =============================================== */

-- USUARIOS -> CREATE = EXEC == USUARIOS_CREATE ''
CREATE PROCEDURE USUARIOS_CREATE
(
    @usuario VARCHAR(16),
    @correo VARCHAR(320),
    @clave CHAR(64),
    @dni CHAR(8),
    @apePater VARCHAR(15),
    @apeMater VARCHAR(15),
    @nombres VARCHAR(45),
    @sexo CHAR(1),
    @fec_nac DATE,
    @id_idioma CHAR(8)
)
AS BEGIN 
    DECLARE @id CHAR(8)
    SELECT @id = 'USR' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM USUARIOS
    INSERT INTO USUARIOS VALUES (@id, @usuario, @correo, @clave, @dni, @apePater, @apeMater, @nombre, @sexo, @fec_nac,@id_idioma, '1')
END
GO 

-- USUARIOS -> READ ALL = EXEC USUARIOS_READ_ALL
CREATE PROCEDURE USUARIOS_READ_ALL
AS
    SELECT * FROM USUARIOS
GO

-- USUARIOS -> READ ACTIVES == EXEC USUARIOS_READ_ACTIVES
CREATE PROCEDURE USUARIOS_READ_ACTIVES
AS
    SELECT * FROM USUARIOS WHERE estado = '1'
GO

-- USUARIOS -> READ INACTIVES == EXEC USUARIO_READ_INACTIVES
CREATE PROCEDURE USUARIOS_READ_INACTIVES
AS
    SELECT * FROM USUARIOS WHERE estado = '0'
GO

-- USUARIOS -> READ ONE == EXEC USUARIOS_READ_ONE
CREATE PROCEDURE USUARIOS_READ_ONE
@id CHAR(8)
AS
    SELECT * FROM USUARIOS WHERE id = @id
GO



/*  USUARIO Y CORREO PARA SEARCH* 201 107*/
