USE MANAGE_IT
GO

/* =========================================== */
/* INICIO PROCEDIMIENTOS ALMACENADOS SERVICIOS */

-- SERVICIOS -> CREATE == EXEC SERVICIOS_CREATE 'Abarrote'
CREATE PROCEDURE SERVICIOS_CREATE
@servicio VARCHAR(45)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'SER' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM SERVICIOS
	INSERT INTO SERVICIOS VALUES (@id, @servicio, '1')
END
GO

-- SERVICIOS -> READ ALL == EXEC SERVICIOS_READ_ALL
CREATE PROCEDURE SERVICIOS_READ_ALL
AS
	SELECT * FROM SERVICIOS
GO

-- SERVICIOS -> READ ACTIVES == EXEC SERVICIOS_READ_ACTIVES
CREATE PROCEDURE SERVICIOS_READ_ACTIVES
AS
	SELECT * FROM SERVICIOS WHERE estado = '1'
GO

-- SERVICIOS -> READ INACTIVES == EXEC SERVICIOS_READ_INACTIVES
CREATE PROCEDURE SERVICIOS_READ_INACTIVES
AS
	SELECT * FROM SERVICIOS WHERE estado = '0'
GO

-- SERVICIOS -> READ ONE == EXEC SERVICIOS_READ_ONE
CREATE PROCEDURE SERVICIOS_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM SERVICIOS WHERE id = @id
GO

-- SERVICIOS -> SEARCH == EXEC SERVICIOS_SEARCH
CREATE PROCEDURE SERVICIOS_SEARCH
@servicio VARCHAR(12)
AS
	SELECT * FROM SERVICIOS WHERE descripcion LIKE(CONCAT('%', @servicio, '%'))
GO

-- SERVICIOS -> UPDATE == EXEC SERVICIOS_UPDATE
CREATE PROCEDURE SERVICIOS_UPDATE
@id		CHAR(8),
@servicio VARCHAR(12),
@estado BIT
AS
	UPDATE SERVICIOS SET
	servicio = @servicio,
	estado = @estado
	WHERE id = @id
GO

-- SERVICIOS -> CHANGE STATUS == EXEC SERVICIOS_CHANGE_STATUS
CREATE PROCEDURE SERVICIOS_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM SERVICIOS WHERE id = @id
	IF @estado = 1
		UPDATE SERVICIOS SET estado = '0' WHERE id = @id
	ELSE
		UPDATE SERVICIOS SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS SERVICIOS */
/* ====================================== */


/* ========================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS IDIOMAS */

-- IDIOMAS -> CREATE == EXEC IDIOMAS_CREATE 'English'
CREATE PROCEDURE IDIOMAS_CREATE
@idioma VARCHAR(12)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'IDI' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM IDIOMAS
	INSERT INTO IDIOMAS VALUES (@id, @idioma, '1')
END
GO

-- IDIOMAS -> READ ALL == EXEC IDIOMAS_READ_ALL
CREATE PROCEDURE IDIOMAS_READ_ALL
AS
	SELECT * FROM IDIOMAS
GO

-- IDIOMAS -> READ ACTIVES == EXEC IDIOMAS_READ_ACTIVES
CREATE PROCEDURE IDIOMAS_READ_ACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '1'
GO

-- IDIOMAS -> READ INACTIVES == EXEC IDIOMAS_READ_INACTIVES
CREATE PROCEDURE IDIOMAS_READ_INACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '0'
GO

-- IDIOMAS -> READ ONE == EXEC IDIOMAS_READ_ONE
CREATE PROCEDURE IDIOMAS_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM IDIOMAS WHERE id = @id
GO

-- IDIOMAS -> SEARCH == EXEC IDIOMAS_SEARCH
CREATE PROCEDURE IDIOMAS_SEARCH
@idioma VARCHAR(12)
AS
	SELECT * FROM IDIOMAS WHERE idioma LIKE(CONCAT('%', @idioma, '%'))
GO

-- IDIOMAS -> UPDATE == EXEC IDIOMAS_UPDATE
CREATE PROCEDURE IDIOMAS_UPDATE
@id		CHAR(8),
@idioma VARCHAR(12),
@estado BIT
AS
	UPDATE IDIOMAS SET
	idioma = @idioma,
	estado = @estado
	WHERE id = @id
GO

-- IDIOMAS -> CHANGE STATUS == EXEC IDIOMAS_CHANGE_STATUS
CREATE PROCEDURE IDIOMAS_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM IDIOMAS WHERE id = @id
	IF @estado = 1
		UPDATE IDIOMAS SET estado = '0' WHERE id = @id
	ELSE
		UPDATE IDIOMAS SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS IDIOMAS */
/* ====================================== */


/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS PERSONA_NATURAL */

-- PERSONA_NATURAL -> CREATE == EXEC PERSONA_NATURAL_CREATE 'English'
CREATE PROCEDURE PERSONA_NATURAL_CREATE
@apePater VARCHAR(15),
@apeMater VARCHAR(15),
@nombres VARCHAR(45),
@dni CHAR(8),
@id_servicio CHAR(8),
@tel1 VARCHAR(15),
@tel2 VARCHAR(15),
@correo VARCHAR(320),
@direccion VARCHAR(250)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'PNA' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM PERSONA_NATURAL
	INSERT INTO PERSONA_NATURAL VALUES (
		@id, @apePater, @apeMater, @nombres, @dni,
		@id_servicio, @tel1, @tel2, @correo, @direccion, '1'
	)
END
GO

-- PERSONA_NATURAL -> READ ALL == EXEC PERSONA_NATURAL_READ_ALL
CREATE PROCEDURE PERSONA_NATURAL_READ_ALL
AS
	SELECT * FROM PERSONA_NATURAL
GO

-- PERSONA_NATURAL -> READ ACTIVES == EXEC PERSONA_NATURAL_READ_ACTIVES
CREATE PROCEDURE PERSONA_NATURAL_READ_ACTIVES
AS
	SELECT * FROM PERSONA_NATURAL WHERE	estado = '1'
GO

-- PERSONA_NATURAL -> READ INACTIVES == EXEC PERSONA_NATURAL_READ_INACTIVES
CREATE PROCEDURE PERSONA_NATURAL_READ_INACTIVES
AS
	SELECT * FROM PERSONA_NATURAL WHERE	estado = '0'
GO

-- PERSONA_NATURAL -> READ ONE == EXEC PERSONA_NATURAL_READ_ONE
CREATE PROCEDURE PERSONA_NATURAL_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM PERSONA_NATURAL WHERE id = @id
GO

-- PERSONA_NATURAL -> SEARCH == EXEC PERSONA_NATURAL_SEARCH
CREATE PROCEDURE PERSONA_NATURAL_SEARCH
@search VARCHAR(50)
AS
	SELECT * FROM PERSONA_NATURAL WHERE
		apePater LIKE(CONCAT('%', @search, '%')) OR
		apeMater LIKE(CONCAT('%', @search, '%')) OR
		nombres LIKE(CONCAT('%', @search, '%')) OR
		dni LIKE(CONCAT('%', @search, '%'))
GO

-- PERSONA_NATURAL -> UPDATE == EXEC PERSONA_NATURAL_UPDATE
CREATE PROCEDURE PERSONA_NATURAL_UPDATE
@id CHAR(8),
@apePater VARCHAR(15),
@apeMater VARCHAR(15),
@nombres VARCHAR(45),
@dni CHAR(8),
@id_servicio CHAR(8),
@tel1 VARCHAR(15),
@tel2 VARCHAR(15),
@correo VARCHAR(320),
@direccion VARCHAR(250),
@estado BIT
AS
	UPDATE PERSONA_NATURAL SET
	apePater = @apePater,
	apeMater = @apeMater,
	nombres = @nombres,
	dni = @dni,
	id_servicio = @id_servicio,
	tel1 = @tel1,
	tel2 = @tel2,
	correo = @correo,
	direccion = @direccion,
	estado = @estado
	WHERE id = @id
GO

-- PERSONA_NATURAL -> CHANGE STATUS == EXEC PERSONA_NATURAL_CHANGE_STATUS
CREATE PROCEDURE PERSONA_NATURAL_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM PERSONA_NATURAL WHERE id = @id
	IF @estado = 1
		UPDATE PERSONA_NATURAL SET estado = '0' WHERE id = @id
	ELSE
		UPDATE PERSONA_NATURAL SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS PERSONA_NATURAL */
/* ====================================== */


/* ================================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS PERSONA_JURIDICA */

-- PERSONA_JURIDICA -> CREATE == EXEC PERSONA_JURIDICA_CREATE 'English'
CREATE PROCEDURE PERSONA_JURIDICA_CREATE
@razonSocial VARCHAR(250),
@ruc CHAR(11),
@id_servicio CHAR(8),
@tel1 VARCHAR(15),
@tel2 VARCHAR(15),
@correo VARCHAR(320),
@direccion VARCHAR(320)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'PJU' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM PERSONA_NATURAL
	INSERT INTO PERSONA_JURIDICA VALUES (
		@id, @razonSocial, @ruc, @id_servicio,
		@tel1, @tel2, @correo, @direccion, '1'
	)
END
GO

-- PERSONA_JURIDICA -> READ ALL == EXEC PERSONA_JURIDICA_READ_ALL
CREATE PROCEDURE PERSONA_JURIDICA_READ_ALL
AS
	SELECT * FROM PERSONA_JURIDICA
GO

-- PERSONA_JURIDICA -> READ ACTIVES == EXEC PERSONA_JURIDICA_READ_ACTIVES
CREATE PROCEDURE PERSONA_JURIDICA_READ_ACTIVES
AS
	SELECT * FROM PERSONA_JURIDICA WHERE	estado = '1'
GO

-- PERSONA_JURIDICA -> READ INACTIVES == EXEC PERSONA_JURIDICA_READ_INACTIVES
CREATE PROCEDURE PERSONA_JURIDICA_READ_INACTIVES
AS
	SELECT * FROM PERSONA_JURIDICA WHERE	estado = '0'
GO

-- PERSONA_JURIDICA -> READ ONE == EXEC PERSONA_JURIDICA_READ_ONE
CREATE PROCEDURE PERSONA_JURIDICA_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM PERSONA_JURIDICA WHERE id = @id
GO

-- PERSONA_JURIDICA -> SEARCH == EXEC PERSONA_JURIDICA_SEARCH
CREATE PROCEDURE PERSONA_JURIDICA_SEARCH
@search VARCHAR(50)
AS
	SELECT * FROM PERSONA_JURIDICA WHERE
		razonSocial LIKE(CONCAT('%', @search, '%')) OR
		ruc LIKE(CONCAT('%', @search, '%'))
GO

-- PERSONA_JURIDICA -> UPDATE == EXEC PERSONA_JURIDICA_UPDATE
CREATE PROCEDURE PERSONA_JURIDICA_UPDATE
@id CHAR(8),
@razonSocial VARCHAR(250),
@ruc CHAR(11),
@id_servicio CHAR(8),
@tel1 VARCHAR(15),
@tel2 VARCHAR(15),
@correo VARCHAR(320),
@direccion VARCHAR(320),
@estado BIT
AS
	UPDATE PERSONA_JURIDICA SET
	razonSocial = @razonSocial,
	ruc = @ruc,
	id_servicio = @id_servicio,
	tel1 = @tel1,
	tel2 = @tel2,
	correo = @correo,
	direccion = @direccion,
	estado = @estado
	WHERE id = @id
GO

-- PERSONA_JURIDICA -> CHANGE STATUS == EXEC PERSONA_JURIDICA_CHANGE_STATUS
CREATE PROCEDURE PERSONA_JURIDICA_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM PERSONA_JURIDICA WHERE id = @id
	IF @estado = 1
		UPDATE PERSONA_JURIDICA SET estado = '0' WHERE id = @id
	ELSE
		UPDATE PERSONA_JURIDICA SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS PERSONA_JURIDICA */
/* ====================================== */