USE MANAGE_IT
GO

/* =========================================== */
/* INICIO PROCEDIMIENTOS ALMACENADOS SERVICIOS */

-- SERVICIOS -> CREATE == EXEC SERVICIOS_CREATE 'Abarrote'
CREATE PROCEDURE SERVICIOS_CREATE
@servicio VARCHAR(45)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'SER' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM SERVICIOS
	INSERT INTO SERVICIOS VALUES (@id, @servicio, '1')
END
GO

-- SERVICIOS -> READ ALL == EXEC SERVICIOS_READ_ALL
CREATE PROCEDURE SERVICIOS_READ_ALL
AS
	SELECT * FROM SERVICIOS
GO

-- SERVICIOS -> READ ACTIVES == EXEC SERVICIOS_READ_ACTIVES
CREATE PROCEDURE SERVICIOS_READ_ACTIVES
AS
	SELECT * FROM SERVICIOS WHERE estado = '1'
GO

-- SERVICIOS -> READ INACTIVES == EXEC SERVICIOS_READ_INACTIVES
CREATE PROCEDURE SERVICIOS_READ_INACTIVES
AS
	SELECT * FROM SERVICIOS WHERE estado = '0'
GO

-- SERVICIOS -> READ ONE == EXEC SERVICIOS_READ_ONE
CREATE PROCEDURE SERVICIOS_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM SERVICIOS WHERE id = @id
GO

-- SERVICIOS -> SEARCH == EXEC SERVICIOS_SEARCH
CREATE PROCEDURE SERVICIOS_SEARCH
@servicio VARCHAR(12)
AS
	SELECT * FROM SERVICIOS WHERE descripcion LIKE(CONCAT('%', @servicio, '%'))
GO

-- SERVICIOS -> UPDATE == EXEC SERVICIOS_UPDATE
CREATE PROCEDURE SERVICIOS_UPDATE
@id		CHAR(8),
@servicio VARCHAR(12),
@estado BIT
AS
	UPDATE SERVICIOS SET
	servicio = @servicio,
	estado = @estado
	WHERE id = @id
GO

-- SERVICIOS -> CHANGE STATUS == EXEC SERVICIOS_CHANGE_STATUS
CREATE PROCEDURE SERVICIOS_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM SERVICIOS WHERE id = @id
	IF @estado = 1
		UPDATE SERVICIOS SET estado = '0' WHERE id = @id
	ELSE
		UPDATE SERVICIOS SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS SERVICIOS */
/* ====================================== */


/* ========================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS PERSONA_NATURAL */

-- IDIOMAS -> CREATE == EXEC IDIOMAS_CREATE 'English'
CREATE PROCEDURE IDIOMAS_CREATE
@idioma VARCHAR(12)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'IDI' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM IDIOMAS
	INSERT INTO IDIOMAS VALUES (@id, @idioma, '1')
END
GO

-- IDIOMAS -> READ ALL == EXEC IDIOMAS_READ_ALL
CREATE PROCEDURE IDIOMAS_READ_ALL
AS
	SELECT * FROM IDIOMAS
GO

-- IDIOMAS -> READ ACTIVES == EXEC IDIOMAS_READ_ACTIVES
CREATE PROCEDURE IDIOMAS_READ_ACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '1'
GO

-- IDIOMAS -> READ INACTIVES == EXEC IDIOMAS_READ_INACTIVES
CREATE PROCEDURE IDIOMAS_READ_INACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '0'
GO

-- IDIOMAS -> READ ONE == EXEC IDIOMAS_READ_ONE
CREATE PROCEDURE IDIOMAS_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM IDIOMAS WHERE id = @id
GO

-- IDIOMAS -> SEARCH == EXEC IDIOMAS_SEARCH
CREATE PROCEDURE IDIOMAS_SEARCH
@idioma VARCHAR(12)
AS
	SELECT * FROM IDIOMAS WHERE idioma LIKE(CONCAT('%', @idioma, '%'))
GO

-- IDIOMAS -> UPDATE == EXEC IDIOMAS_UPDATE
CREATE PROCEDURE IDIOMAS_UPDATE
@id		CHAR(8),
@idioma VARCHAR(12),
@estado BIT
AS
	UPDATE IDIOMAS SET
	idioma = @idioma,
	estado = @estado
	WHERE id = @id
GO

-- IDIOMAS -> CHANGE STATUS == EXEC IDIOMAS_CHANGE_STATUS
CREATE PROCEDURE IDIOMAS_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM IDIOMAS WHERE id = @id
	IF @estado = 1
		UPDATE IDIOMAS SET estado = '0' WHERE id = @id
	ELSE
		UPDATE IDIOMAS SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS IDIOMAS */
/* ====================================== */


/* ========================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS IDIOMAS */

-- IDIOMAS -> CREATE == EXEC IDIOMAS_CREATE 'English'
CREATE PROCEDURE IDIOMAS_CREATE
@idioma VARCHAR(12)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'IDI' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM IDIOMAS
	INSERT INTO IDIOMAS VALUES (@id, @idioma, '1')
END
GO

-- IDIOMAS -> READ ALL == EXEC IDIOMAS_READ_ALL
CREATE PROCEDURE IDIOMAS_READ_ALL
AS
	SELECT * FROM IDIOMAS
GO

-- IDIOMAS -> READ ACTIVES == EXEC IDIOMAS_READ_ACTIVES
CREATE PROCEDURE IDIOMAS_READ_ACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '1'
GO

-- IDIOMAS -> READ INACTIVES == EXEC IDIOMAS_READ_INACTIVES
CREATE PROCEDURE IDIOMAS_READ_INACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '0'
GO

-- IDIOMAS -> READ ONE == EXEC IDIOMAS_READ_ONE
CREATE PROCEDURE IDIOMAS_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM IDIOMAS WHERE id = @id
GO

-- IDIOMAS -> SEARCH == EXEC IDIOMAS_SEARCH
CREATE PROCEDURE IDIOMAS_SEARCH
@idioma VARCHAR(12)
AS
	SELECT * FROM IDIOMAS WHERE idioma LIKE(CONCAT('%', @idioma, '%'))
GO

-- IDIOMAS -> UPDATE == EXEC IDIOMAS_UPDATE
CREATE PROCEDURE IDIOMAS_UPDATE
@id		CHAR(8),
@idioma VARCHAR(12),
@estado BIT
AS
	UPDATE IDIOMAS SET
	idioma = @idioma,
	estado = @estado
	WHERE id = @id
GO

-- IDIOMAS -> CHANGE STATUS == EXEC IDIOMAS_CHANGE_STATUS
CREATE PROCEDURE IDIOMAS_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM IDIOMAS WHERE id = @id
	IF @estado = 1
		UPDATE IDIOMAS SET estado = '0' WHERE id = @id
	ELSE
		UPDATE IDIOMAS SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS IDIOMAS */
/* ====================================== */
