/* ========================================= */
/* INICIO PROCEDIMIENTOS ALMACENADOS IDIOMAS */
USE MANAGE_IT
GO

-- IDIOMAS -> CREATE == EXEC IDIOMAS_CREATE 'English'
CREATE PROCEDURE IDIOMAS_CREATE
@idioma VARCHAR(12)
AS BEGIN
	DECLARE @id CHAR(8)
	SELECT @id = 'IDI' + RIGHT('00000' + LTRIM(STR(COUNT(*) + 1)), 5) FROM IDIOMAS
	INSERT INTO IDIOMAS VALUES (@id, @idioma, '1')
END
GO

-- IDIOMAS -> READ ALL == EXEC IDIOMAS_READ_ALL
CREATE PROCEDURE IDIOMAS_READ_ALL
AS
	SELECT * FROM IDIOMAS
GO

-- IDIOMAS -> READ ACTIVES == EXEC IDIOMAS_READ_ACTIVES
CREATE PROCEDURE IDIOMAS_READ_ACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '1'
GO

-- IDIOMAS -> READ INACTIVES == EXEC IDIOMAS_READ_INACTIVES
CREATE PROCEDURE IDIOMAS_READ_INACTIVES
AS
	SELECT * FROM IDIOMAS WHERE	estado = '0'
GO

-- IDIOMAS -> READ ONE == EXEC IDIOMAS_READ_ONE
CREATE PROCEDURE IDIOMAS_READ_ONE
@id CHAR(8)
AS
	SELECT * FROM IDIOMAS WHERE id = @id
GO

-- IDIOMAS -> SEARCH == EXEC IDIOMAS_SEARCH
CREATE PROCEDURE IDIOMAS_SEARCH
@idioma VARCHAR(12)
AS
	SELECT * FROM IDIOMAS WHERE idioma LIKE(CONCAT('%', @idioma, '%'))
GO

-- IDIOMAS -> UPDATE == EXEC IDIOMAS_UPDATE
CREATE PROCEDURE IDIOMAS_UPDATE
@id		CHAR(8),
@idioma VARCHAR(12),
@estado BIT
AS
	UPDATE IDIOMAS SET
	idioma = @idioma,
	estado = @estado
	WHERE id = @id
GO

-- IDIOMAS -> CHANGE STATUS == EXEC IDIOMAS_CHANGE_STATUS
CREATE PROCEDURE IDIOMAS_CHANGE_STATUS
@id CHAR(8)
AS
	DECLARE @estado BIT
	SELECT @estado = estado FROM IDIOMAS WHERE id = @id
	IF @estado = 1
		UPDATE IDIOMAS SET estado = '0' WHERE id = @id
	ELSE
		UPDATE IDIOMAS SET estado = '1' WHERE id = @id
GO

/* FIN PROCEDIMIENTOS ALMACENADOS IDIOMAS */
/* ====================================== */


